# Generated by Django 3.1.4 on 2020-12-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201228_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=30),
        ),
    ]
