# Generated by Django 3.1.4 on 2020-12-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20201210_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
