# Generated by Django 3.1.4 on 2020-12-10 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201210_0837'),
        ('measurements', '0003_auto_20201210_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customer'),
        ),
    ]
